### ISSUE TITLE
Crash when claiming a quest from the pause menu

### ISSUE THREAD

**Issue by FRBFStudios** [Kingminer7/quests-in-pause#1]
I tried to claim a quest using the button in the pause menu for the first time, and once I clicked the checkmark, the game crashed (This also happened when claiming a quest in the custom quest menu of the Overcharged Main Menu mod, so I think something is wrong with remotely claiming quests in general).
Crashlog:
[2024-08-25_13-11-31.txt](https://github.com/user-attachments/files/16739930/2024-08-25_13-11-31.txt)

**Comment by Kingminer7** [comment]
Sorry for the delay, does this happen without Quests in Pause Menu?

**Comment by FRBFStudios** [comment]
no, as i said, it only happens when claiming a quest from the pause menu using this mod. it doesn't happen in the vanilla quest menu.

**Comment by Kingminer7** [comment]
Does this one still crash?
https://github.com/Kingminer7/quests-in-pause/releases/download/testing/km7dev.quests_in_pause_menu.geode

**Comment by FRBFStudios** [comment]
it doesn't seem like it. however, now the sound effect for claiming a quest doesn't play.

**Comment by Kingminer7** [comment]
> it doesn't seem like it. however, now the sound effect for claiming a quest doesn't play.

That is something I don't think I can control - RobTop pauses the SFX audio channel or something when the pause menu is open. I don't know of a way to fix that, but if I find a way then I'll update for that.

I will push the crash fix to the index though. Thank you for testing that build.
