### ISSUE TITLE
Quest in pause crash mid-game.

### ISSUE THREAD

**Issue by NonCloud9** [Kingminer7/quests-in-pause#2]
I usually claim the quest at the very beginning of the level but this time after i got the coins and stars quest from the weekly i didn't claim it, not after i wanted to do the weekly again from the main servers and in like 10% (Casino blitz 1st coin route) i wanted to claim the rewards from the pause menu and the game crash.

Here's the crash log:
 
[2024-08-29_16-14-40.txt](https://github.com/user-attachments/files/16806136/2024-08-29_16-14-40.txt)

**Comment by Kingminer7** [comment]
Does this happen if you try claiming quests from the normal menu? I cannot recreate it

**Comment by NonCloud9** [comment]
No, just mid-level.

After that i claimed the rewards on the normal quests menu and it worked fine.

**Comment by Kingminer7** [comment]
> No, just mid-level.
> 
> After that i claimed the rewards on the normal quests menu and it worked fine.

I honestly have no idea what causes this - if it happens again then let me know

**Comment by Kingminer7** [comment]
This is fixed in 1.0.2. Currently the index is down, so I can't push the update. You can still install it manually from releases.
https://github.com/Kingminer7/quests-in-pause/releases/tag/1.0.2
